/* ─────────────────────────────────────────────
   Widget Types
───────────────────────────────────────────── */

/**
 * All supported widget types.
 *
 * Common ECharts types are listed explicitly for discoverability.
 * Use `'chart'` as a generic escape hatch for any ECharts series type
 * not listed here (e.g. custom, parallel, themeRiver, etc.).
 * The frontend passes chartConfig straight to ECharts regardless of
 * this value — it only affects layout sizing (KPI vs chart height).
 */
export type WidgetType =
  | 'kpi'
  // ── Common chart types ──
  | 'bar'
  | 'line'
  | 'area'
  | 'pie'
  | 'scatter'
  // ── Statistical / analytical ──
  | 'heatmap'
  | 'boxplot'
  | 'candlestick'
  | 'histogram'
  // ── Hierarchical / relational ──
  | 'treemap'
  | 'sunburst'
  | 'sankey'
  | 'graph'
  | 'tree'
  // ── Specialty ──
  | 'radar'
  | 'funnel'
  | 'gauge'
  | 'map'
  | 'waterfall'
  // ── Catch-all for any ECharts series type ──
  | 'chart';

/** Grid position & size of a widget within the dashboard grid */
export interface WidgetLayout {
  x: number;
  y: number;
  w: number;
  h: number;
  minW?: number;
  minH?: number;
  maxW?: number;
  maxH?: number;
}

/** Configuration specific to KPI widgets */
export interface KpiConfig {
  value: number;
  prefix?: string;
  suffix?: string;
  change?: number;
  changeLabel?: string;
  icon?: KpiIcon;
  /** Optional sparkline data points for a mini trend line */
  sparkline?: number[];
}

export type KpiIcon = 'revenue' | 'orders' | 'aov' | 'customers' | 'generic';

/**
 * ECharts option object.
 * We keep this as Record<string, unknown> because ECharts options
 * are deeply nested and the Python backend will generate them directly.
 * The frontend passes this straight to echarts-for-react.
 */
export type EChartsConfig = Record<string, unknown>;

/** A single widget (KPI card, chart, etc.) */
export interface Widget {
  /** Unique identifier — generated by the backend or frontend */
  id: string;
  /** Human-readable title shown in the widget header */
  title: string;
  /**
   * Visual type — determines rendering strategy.
   * Variants like stacked bars, clustered bars, horizontal bars,
   * donut charts, etc. are controlled via `chartConfig`, not this field.
   * This field only affects layout sizing (KPI vs chart).
   */
  type: WidgetType;
  /** Grid placement — if omitted, the layout engine auto-computes it */
  layout?: WidgetLayout;
  /**
   * Chart configuration:
   * - For KPI widgets  → KpiConfig
   * - For chart widgets → EChartsConfig (passed directly to echarts-for-react)
   */
  chartConfig: KpiConfig | EChartsConfig;
  /**
   * Data configuration, typically containing the SQL query and field mappings.
   */
  dataConfig?: Record<string, unknown>;
}

/* ─────────────────────────────────────────────
   Dashboard Types
───────────────────────────────────────────── */

/** Dashboard metadata */
export interface DashboardMeta {
  /** Unique dashboard identifier */
  id: string;
  /** Display name */
  name: string;
  /** Optional description / subtitle */
  description?: string;
  /** ISO-8601 creation timestamp */
  createdAt: string;
  /** ISO-8601 last-updated timestamp */
  updatedAt: string;
  /** Freeform tags for categorisation */
  tags?: string[];
  /** Source classification returned by backend (e.g. manual, template) */
  source?: string;
}

/** Full dashboard definition — the canonical shape exchanged with the backend */
export interface Dashboard {
  meta: DashboardMeta;
  widgets: Widget[];
}

/* ─────────────────────────────────────────────
   API Payload Types
───────────────────────────────────────────── */

/**
 * Action discriminator — tells the frontend what to do
 * with the incoming payload.
 */
export type ApiAction = 'create' | 'update';

/**
 * The top-level JSON payload sent by the Python backend.
 *
 * • action: "create"  — render a brand-new dashboard
 * • action: "update"  — patch an existing dashboard
 *                        (only the provided fields are merged)
 */
export interface DashboardApiPayload {
  action: ApiAction;
  dashboard: Dashboard;
}

/**
 * Partial widget update — only the fields present will be merged
 * into the existing widget. `id` is always required to locate the target.
 */
export type WidgetPatch = Pick<Widget, 'id'> & Partial<Omit<Widget, 'id'>>;

/**
 * Granular update payload — allows surgical modifications to
 * an existing dashboard without resending everything.
 */
export interface DashboardPatchPayload {
  action: 'patch';
  dashboardId: string;
  /** Replace dashboard metadata fields (partial) */
  meta?: Partial<DashboardMeta>;
  /** Widgets to add */
  addWidgets?: Widget[];
  /** Widget fields to merge/update (matched by id) */
  updateWidgets?: WidgetPatch[];
  /** Widget IDs to remove */
  removeWidgetIds?: string[];
}

/** Union of all possible inbound payloads */
export type InboundPayload = DashboardApiPayload | DashboardPatchPayload;

/* ─────────────────────────────────────────────
   Date Filtering Types
───────────────────────────────────────────── */

/** Preset values accepted by GET /api/dashboards/{id}?preset=... */
export type DatePreset = 'last_7_days' | 'last_14_days' | 'last_30_days' | 'last_60_days' | 'last_90_days';

/** Custom date range (ISO date strings, inclusive start / exclusive end) */
export interface CustomDateRange {
  startDate: string;
  endDate: string;
}

/* ─────────────────────────────────────────────
   Chat Types (from backend API)
───────────────────────────────────────────── */

export type ChatRole = 'user' | 'assistant' | 'tool';

export interface ChatToolCall {
  id: string;
  name: string;
  args: Record<string, unknown>;
}

export interface ChatMessage {
  role: ChatRole;
  content: string | null;
  /** Magic Mode: synthetic user line from User Proxy AI (SSE `proxy_reply`) */
  proxyAuto?: boolean;
  tool_calls?: ChatToolCall[];
  tool_call_id?: string;
  tool_name?: string;
  /** Present on tool messages when create_react_chart/create_react_kpi was used (GET history) */
  chart?: {
    tool_call_id?: string;
    chart_type?: string;
    title?: string;
    chartConfig: EChartsConfig;
    dataConfig?: Record<string, unknown>;
  };
}

/** One chart rendered in chat (from SSE `chart` event or history tool message with chart) */
export interface ChatChartItem {
  chart_type?: string;
  title?: string;
  chartConfig: EChartsConfig;
  /** SQL query + mappings for dashboard date-filter re-hydration */
  dataConfig?: Record<string, unknown>;
}

export interface SSEStartData {
  status: string;
}

export interface SSETokenData {
  content: string;
}

export interface SSEToolCallStartData {
  tool_call_id: string;
  tool_name: string;
}

export interface SSEToolCallArgsData {
  tool_call_id: string;
  args_chunk: string;
}

export interface SSEToolResultData {
  tool_call_id: string;
  tool_name: string;
  args: string;
  result: string;
}

export interface SSEChartData {
  tool_call_id: string;
  chart_type: string;
  title?: string;
  /** ECharts option object from create_react_chart tool (POST /api/chat SSE `chart` event) */
  chartConfig: EChartsConfig;
  /** SQL query + mappings for dashboard date-filter re-hydration (when available) */
  dataConfig?: Record<string, unknown>;
}

export interface SSEEndData {}

/** Magic Mode: one assistant turn completed; client flushes streaming buffers */
export interface SSESegmentEndData {
  [key: string]: unknown;
}

/** Magic Mode: synthetic user message from User Proxy AI */
export interface SSEProxyReplyData {
  content: string;
}

export interface SSEErrorData {
  detail: string;
}

export type SSEData =
  | SSEStartData
  | SSETokenData
  | SSEToolCallStartData
  | SSEToolCallArgsData
  | SSEToolResultData
  | SSEChartData
  | SSESegmentEndData
  | SSEProxyReplyData
  | SSEEndData
  | SSEErrorData;

/** Request body for POST /api/chat */
export interface ChatSendRequest {
  message: string;
  session_id?: string;
  agent_type?: string;
  llm?: string;
  database?: string;
  /** When agent_type is dashboard */
  dashboard_mode?: 'magic' | 'guided';
  /** Omit to use all tenant datasets */
  selected_datasets?: string[];
  /** Magic Mode: passed to User Proxy for intent alignment */
  magic_dashboard_name?: string;
  magic_goal?: string;
  /** Analyst agent: name of dashboard the user has attached to the chat. */
  attached_dashboard_name?: string;
}

/** GET /api/dashboards/builder/readiness */
export interface DashboardBuilderReadiness {
  status: 'ready' | 'waiting_sync' | 'no_connector';
  message: string;
  datasets: string[];
  has_connector: boolean;
  has_synced_data: boolean;
}

/* ─────────────────────────────────────────────
   Template Types (from backend)
───────────────────────────────────────────── */

/** Template metadata returned by GET /api/templates */
export interface TemplateMeta {
  id: string;
  slug: string;
  name: string;
  description: string;
  platforms: string[];
  tags: string[];
  preview_image?: string | null;
}

/** Template with widget blueprints from GET /api/templates/{slug} */
export interface TemplateWithWidgets extends TemplateMeta {
  is_active: boolean;
  widgets: Array<{
    id: string;
    template_id: string;
    title: string;
    type: WidgetType;
    layout: WidgetLayout;
    chart_config: KpiConfig | EChartsConfig;
    data_config: Record<string, unknown>;
    sort_order: number;
  }>;
}

/* ─────────────────────────────────────────────
   Auth Types (from backend)
───────────────────────────────────────────── */

export type UserRole = 'admin' | 'client';

export interface UserProfile {
  id: string;
  email: string;
  full_name: string | null;
  avatar_url: string | null;
  role: UserRole;
}

export interface AuthResponse {
  access_token: string;
  refresh_token: string;
  user: UserProfile;
}

export interface SignInRequest {
  email: string;
  password: string;
}

/** POST /api/auth/signup */
export interface SignUpRequest {
  email: string;
  password: string;
  full_name?: string;
}

/* ─────────────────────────────────────────────
   Dashboard API response types (Supabase-backed)
───────────────────────────────────────────── */

/** Widget as returned by GET/POST /api/dashboards (single or list) */
export interface ApiWidget {
  id: string;
  dashboard_id?: string;
  title: string;
  type: WidgetType;
  layout: WidgetLayout;
  chart_config: KpiConfig | EChartsConfig;
  data_config?: Record<string, unknown>;
  data_snapshot?: unknown;
  data_refreshed_at?: string | null;
  sort_order: number;
}

/** Dashboard metadata from GET /api/dashboards (list) */
export interface ApiDashboardMeta {
  id: string;
  name: string;
  description?: string | null;
  tags?: string[];
  source?: string;
  template_id?: string | null;
  connection_id?: string | null;
  created_at: string;
  updated_at: string;
}

/** Full dashboard from GET /api/dashboards/{id} or POST /api/dashboards */
export interface ApiDashboard {
  id: string;
  user_id?: string;
  name: string;
  description?: string | null;
  tags?: string[];
  source?: string;
  template_id?: string | null;
  connection_id?: string | null;
  created_at: string;
  updated_at: string;
  widgets: ApiWidget[];
}

/* ─────────────────────────────────────────────
   Connector API (Phase 2/3 — user_connector_configs)
───────────────────────────────────────────── */

/** GET /api/connectors — one row per saved connector config */
export interface UserConnectorConfig {
  id: string;
  user_id: string;
  connector_name: string;
  docker_repository: string;
  docker_image: string;
  config: Record<string, unknown>;
  oauth_meta?: Record<string, unknown> | null;
  selected_streams?: string[] | null;
  sync_mode: 'one_off' | 'recurring';
  sync_frequency_minutes: number;
  is_active: boolean;
  sync_validated: boolean;
  incremental_enabled: boolean;
  last_sync_at?: string | null;
  last_sync_status: string;
  last_sync_error?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}

/** PATCH /api/connectors/{id} */
export interface UserConnectorConfigPatch {
  connector_name?: string;
  docker_image?: string;
  config?: Record<string, unknown>;
  oauth_meta?: Record<string, unknown> | null;
  selected_streams?: string[] | null;
  sync_mode?: 'one_off' | 'recurring';
  sync_frequency_minutes?: number;
  is_active?: boolean;
  sync_validated?: boolean;
  incremental_enabled?: boolean;
}

/** GET /api/connectors/catalog — slim list (no config_schema / oauth_config) */
export interface ConnectorCatalogListItem {
  id: string;
  docker_repository: string;
  name: string;
  docker_image_tag?: string;
  icon_url?: string | null;
  documentation_url?: string | null;
  is_active?: boolean;
  created_at?: string | null;
  updated_at?: string | null;
}

/** GET /api/connectors/catalog/{id or docker_repository} — full row */
export interface ConnectorCatalogDetail extends ConnectorCatalogListItem {
  config_schema?: Record<string, unknown> | null;
  oauth_config?: Record<string, unknown> | null;
}

/** GET /api/connectors/synced-tables (with start_date + end_date for inventory) */
export interface SyncedMonthFile {
  month: string;
  size_bytes?: number | null;
}

export interface StreamInventoryItem {
  stream: string;
  months: SyncedMonthFile[];
}

export interface SyncedTableInfo {
  connector_config_id: string;
  docker_repository: string;
  connector_name: string;
  last_sync_at?: string | null;
  last_sync_status: string;
  last_sync_error?: string | null;
  data_prefix_hint: string;
  synced_tables: string[];
  /** Present when synced-tables is called with start_date and end_date */
  stream_inventory?: StreamInventoryItem[] | null;
}

/** GET /api/connectors/{id}/streams/{stream}/preview */
export interface RawTablePreview {
  columns: string[];
  rows: (string | number | boolean | null)[][];
  limit: number;
  offset: number;
  has_more: boolean;
  months_included: string[];
}
